services:
  api:
    image: airsense.api
    build:
      context: .
      dockerfile: Airsense.API/Dockerfile
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=airsense1234
      - DATABASE_NAME=airsensedb

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: airsensedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: airsense1234
    volumes:
      - ./db/script.sql:/docker-entrypoint-initdb.d/01_script.sql
      - ./db/functions.sql:/docker-entrypoint-initdb.d/02_functions.sql
      - ./db/data.sql:/docker-entrypoint-initdb.d/03_data.sql
